
!global $PARTICIPANT_FONT_COLOR = "#FFFFFF"
!global $PARTICIPANT_BG_COLOR = "#438DD5"
!global $PARTICIPANT_BORDER_COLOR = "#3C7FC0"

skinparam sequence {
    ParticipantBackgroundColor $PARTICIPANT_BG_COLOR
    ParticipantBorderColor $PARTICIPANT_BORDER_COLOR
    ParticipantFontColor $PARTICIPANT_FONT_COLOR
    
    ParticipantShadowing false
}
