
hide <<component_default>> stereotype
hide <<component_new>> stereotype
hide <<component_changed>> stereotype
hide <<component_deprecated>> stereotype
hide <<endpoint_default>> stereotype
hide <<endpoint_new>> stereotype
hide <<endpoint_changed>> stereotype
hide <<endpoint_deprecated>> stereotype
hide <<c4_component>> stereotype
hide <<c4_container>> stereotype
hide <<c4_context>> stereotype
hide <<c4_external>> stereotype
hide <<system>> stereotype
hide <<system_container>> stereotype
hide <<system_context>> stereotype
hide <<system_component>> stereotype
hide <<system_external>> stereotype
hide <<transparant>> stereotype
hide <<business_default>> stereotype
hide <<business_external>> stereotype

skinparam LegendBackgroundColor transparant
skinparam LegendBorderColor transparant


skinparam RectangleBackgroundColor<<transparant>> transparant
skinparam RectangleBorderColor<<transparant>> transparant

' DEFAULT COLORING
skinparam RectangleBackgroundColor<<component_default>> #438DD5
skinparam RectangleBorderColor<<component_default>> #3C7FC0
skinparam RectangleFontColor<<component_default>> #fff
skinparam RectangleBackgroundColor<<endpoint_default>> #438DD5
skinparam RectangleBorderColor<<endpoint_default>> #3C7FC0
skinparam RectangleFontColor<<endpoint_default>> #000
skinparam QueueBackgroundColor<<component_default>> #438DD5
skinparam QueueBorderColor<<component_default>> #3C7FC0
skinparam QueueFontColor<<component_default>> #fff
skinparam QueueBackgroundColor<<endpoint_default>> #438DD5
skinparam QueueBorderColor<<endpoint_default>> #3C7FC0
skinparam QueueFontColor<<endpoint_default>> #000
skinparam DatabaseBackgroundColor<<component_default>> #438DD5
skinparam DatabaseBorderColor<<component_default>> #3C7FC0
skinparam DatabaseFontColor<<component_default>> #fff
skinparam DatabaseBackgroundColor<<endpoint_default>> #438DD5
skinparam DatabaseBorderColor<<endpoint_default>> #3C7FC0
skinparam DatabaseFontColor<<endpoint_default>> #000
skinparam FileBackgroundColor<<component_default>> #438DD5
skinparam FileBorderColor<<component_default>> #3C7FC0
skinparam FileFontColor<<component_default>> #fff
skinparam FileBackgroundColor<<endpoint_default>> #438DD5
skinparam FileBorderColor<<endpoint_default>> #3C7FC0
skinparam FileFontColor<<endpoint_default>> #000
skinparam HexagonBackgroundColor<<component_default>> #438DD5
skinparam HexagonBorderColor<<component_default>> #3C7FC0
skinparam HexagonFontColor<<component_default>> #fff
skinparam HexagonBackgroundColor<<endpoint_default>> #438DD5
skinparam HexagonBorderColor<<endpoint_default>> #3C7FC0
skinparam HexagonFontColor<<endpoint_default>> #000
skinparam InterfaceBackgroundColor<<component_default>> #438DD5
skinparam InterfaceBorderColor<<component_default>> #3C7FC0
skinparam InterfaceFontColor<<component_default>> #fff
skinparam InterfaceBackgroundColor<<endpoint_default>> #438DD5
skinparam InterfaceBorderColor<<endpoint_default>> #3C7FC0
skinparam InterfaceFontColor<<endpoint_default>> #000
skinparam CircleBackgroundColor<<component_default>> #438DD5
skinparam CircleBorderColor<<component_default>> #3C7FC0
skinparam CircleFontColor<<component_default>> #fff
skinparam CircleBackgroundColor<<endpoint_default>> #438DD5
skinparam CircleBorderColor<<endpoint_default>> #3C7FC0
skinparam CircleFontColor<<endpoint_default>> #000
skinparam RectangleBackgroundColor<<component_new>> #198e25
skinparam RectangleBorderColor<<component_new>> #0b8418
skinparam RectangleFontColor<<component_new>> #fff
skinparam RectangleBackgroundColor<<endpoint_new>> #198e25
skinparam RectangleBorderColor<<endpoint_new>> #0b8418
skinparam RectangleFontColor<<endpoint_new>> #000
skinparam QueueBackgroundColor<<component_new>> #198e25
skinparam QueueBorderColor<<component_new>> #0b8418
skinparam QueueFontColor<<component_new>> #fff
skinparam QueueBackgroundColor<<endpoint_new>> #198e25
skinparam QueueBorderColor<<endpoint_new>> #0b8418
skinparam QueueFontColor<<endpoint_new>> #000
skinparam DatabaseBackgroundColor<<component_new>> #198e25
skinparam DatabaseBorderColor<<component_new>> #0b8418
skinparam DatabaseFontColor<<component_new>> #fff
skinparam DatabaseBackgroundColor<<endpoint_new>> #198e25
skinparam DatabaseBorderColor<<endpoint_new>> #0b8418
skinparam DatabaseFontColor<<endpoint_new>> #000
skinparam FileBackgroundColor<<component_new>> #198e25
skinparam FileBorderColor<<component_new>> #0b8418
skinparam FileFontColor<<component_new>> #fff
skinparam FileBackgroundColor<<endpoint_new>> #198e25
skinparam FileBorderColor<<endpoint_new>> #0b8418
skinparam FileFontColor<<endpoint_new>> #000
skinparam HexagonBackgroundColor<<component_new>> #198e25
skinparam HexagonBorderColor<<component_new>> #0b8418
skinparam HexagonFontColor<<component_new>> #fff
skinparam HexagonBackgroundColor<<endpoint_new>> #198e25
skinparam HexagonBorderColor<<endpoint_new>> #0b8418
skinparam HexagonFontColor<<endpoint_new>> #000
skinparam InterfaceBackgroundColor<<component_new>> #198e25
skinparam InterfaceBorderColor<<component_new>> #0b8418
skinparam InterfaceFontColor<<component_new>> #fff
skinparam InterfaceBackgroundColor<<endpoint_new>> #198e25
skinparam InterfaceBorderColor<<endpoint_new>> #0b8418
skinparam InterfaceFontColor<<endpoint_new>> #000
skinparam CircleBackgroundColor<<component_new>> #198e25
skinparam CircleBorderColor<<component_new>> #0b8418
skinparam CircleFontColor<<component_new>> #fff
skinparam CircleBackgroundColor<<endpoint_new>> #198e25
skinparam CircleBorderColor<<endpoint_new>> #0b8418
skinparam CircleFontColor<<endpoint_new>> #000
skinparam RectangleBackgroundColor<<component_changed>> #9241cc
skinparam RectangleBorderColor<<component_changed>> #7514ba
skinparam RectangleFontColor<<component_changed>> #fff
skinparam RectangleBackgroundColor<<endpoint_changed>> #9241cc
skinparam RectangleBorderColor<<endpoint_changed>> #7514ba
skinparam RectangleFontColor<<endpoint_changed>> #000
skinparam QueueBackgroundColor<<component_changed>> #9241cc
skinparam QueueBorderColor<<component_changed>> #7514ba
skinparam QueueFontColor<<component_changed>> #fff
skinparam QueueBackgroundColor<<endpoint_changed>> #9241cc
skinparam QueueBorderColor<<endpoint_changed>> #7514ba
skinparam QueueFontColor<<endpoint_changed>> #000
skinparam DatabaseBackgroundColor<<component_changed>> #9241cc
skinparam DatabaseBorderColor<<component_changed>> #7514ba
skinparam DatabaseFontColor<<component_changed>> #fff
skinparam DatabaseBackgroundColor<<endpoint_changed>> #9241cc
skinparam DatabaseBorderColor<<endpoint_changed>> #7514ba
skinparam DatabaseFontColor<<endpoint_changed>> #000
skinparam FileBackgroundColor<<component_changed>> #9241cc
skinparam FileBorderColor<<component_changed>> #7514ba
skinparam FileFontColor<<component_changed>> #fff
skinparam FileBackgroundColor<<endpoint_changed>> #9241cc
skinparam FileBorderColor<<endpoint_changed>> #7514ba
skinparam FileFontColor<<endpoint_changed>> #000
skinparam HexagonBackgroundColor<<component_changed>> #9241cc
skinparam HexagonBorderColor<<component_changed>> #7514ba
skinparam HexagonFontColor<<component_changed>> #fff
skinparam HexagonBackgroundColor<<endpoint_changed>> #9241cc
skinparam HexagonBorderColor<<endpoint_changed>> #7514ba
skinparam HexagonFontColor<<endpoint_changed>> #000
skinparam InterfaceBackgroundColor<<component_changed>> #9241cc
skinparam InterfaceBorderColor<<component_changed>> #7514ba
skinparam InterfaceFontColor<<component_changed>> #fff
skinparam InterfaceBackgroundColor<<endpoint_changed>> #9241cc
skinparam InterfaceBorderColor<<endpoint_changed>> #7514ba
skinparam InterfaceFontColor<<endpoint_changed>> #000
skinparam CircleBackgroundColor<<component_changed>> #9241cc
skinparam CircleBorderColor<<component_changed>> #7514ba
skinparam CircleFontColor<<component_changed>> #fff
skinparam CircleBackgroundColor<<endpoint_changed>> #9241cc
skinparam CircleBorderColor<<endpoint_changed>> #7514ba
skinparam CircleFontColor<<endpoint_changed>> #000
skinparam RectangleBackgroundColor<<component_deprecated>> #b5385d
skinparam RectangleBorderColor<<component_deprecated>> #aa1743
skinparam RectangleFontColor<<component_deprecated>> #fff
skinparam RectangleBackgroundColor<<endpoint_deprecated>> #b5385d
skinparam RectangleBorderColor<<endpoint_deprecated>> #aa1743
skinparam RectangleFontColor<<endpoint_deprecated>> #000
skinparam QueueBackgroundColor<<component_deprecated>> #b5385d
skinparam QueueBorderColor<<component_deprecated>> #aa1743
skinparam QueueFontColor<<component_deprecated>> #fff
skinparam QueueBackgroundColor<<endpoint_deprecated>> #b5385d
skinparam QueueBorderColor<<endpoint_deprecated>> #aa1743
skinparam QueueFontColor<<endpoint_deprecated>> #000
skinparam DatabaseBackgroundColor<<component_deprecated>> #b5385d
skinparam DatabaseBorderColor<<component_deprecated>> #aa1743
skinparam DatabaseFontColor<<component_deprecated>> #fff
skinparam DatabaseBackgroundColor<<endpoint_deprecated>> #b5385d
skinparam DatabaseBorderColor<<endpoint_deprecated>> #aa1743
skinparam DatabaseFontColor<<endpoint_deprecated>> #000
skinparam FileBackgroundColor<<component_deprecated>> #b5385d
skinparam FileBorderColor<<component_deprecated>> #aa1743
skinparam FileFontColor<<component_deprecated>> #fff
skinparam FileBackgroundColor<<endpoint_deprecated>> #b5385d
skinparam FileBorderColor<<endpoint_deprecated>> #aa1743
skinparam FileFontColor<<endpoint_deprecated>> #000
skinparam HexagonBackgroundColor<<component_deprecated>> #b5385d
skinparam HexagonBorderColor<<component_deprecated>> #aa1743
skinparam HexagonFontColor<<component_deprecated>> #fff
skinparam HexagonBackgroundColor<<endpoint_deprecated>> #b5385d
skinparam HexagonBorderColor<<endpoint_deprecated>> #aa1743
skinparam HexagonFontColor<<endpoint_deprecated>> #000
skinparam InterfaceBackgroundColor<<component_deprecated>> #b5385d
skinparam InterfaceBorderColor<<component_deprecated>> #aa1743
skinparam InterfaceFontColor<<component_deprecated>> #fff
skinparam InterfaceBackgroundColor<<endpoint_deprecated>> #b5385d
skinparam InterfaceBorderColor<<endpoint_deprecated>> #aa1743
skinparam InterfaceFontColor<<endpoint_deprecated>> #000
skinparam CircleBackgroundColor<<component_deprecated>> #b5385d
skinparam CircleBorderColor<<component_deprecated>> #aa1743
skinparam CircleFontColor<<component_deprecated>> #fff
skinparam CircleBackgroundColor<<endpoint_deprecated>> #b5385d
skinparam CircleBorderColor<<endpoint_deprecated>> #aa1743
skinparam CircleFontColor<<endpoint_deprecated>> #000
skinparam RectangleBackgroundColor<<c4_context>> #08427B
skinparam RectangleBorderColor<<c4_context>> #08427B
skinparam RectangleFontColor<<c4_context>> #fff
skinparam QueueBackgroundColor<<c4_context>> #08427B
skinparam QueueBorderColor<<c4_context>> #08427B
skinparam QueueFontColor<<c4_context>> #fff
skinparam DatabaseBackgroundColor<<c4_context>> #08427B
skinparam DatabaseBorderColor<<c4_context>> #08427B
skinparam DatabaseFontColor<<c4_context>> #fff
skinparam FileBackgroundColor<<c4_context>> #08427B
skinparam FileBorderColor<<c4_context>> #08427B
skinparam FileFontColor<<c4_context>> #fff
skinparam HexagonBackgroundColor<<c4_context>> #08427B
skinparam HexagonBorderColor<<c4_context>> #08427B
skinparam HexagonFontColor<<c4_context>> #fff
skinparam InterfaceBackgroundColor<<c4_context>> #08427B
skinparam InterfaceBorderColor<<c4_context>> #08427B
skinparam InterfaceFontColor<<c4_context>> #fff
skinparam CircleBackgroundColor<<c4_context>> #08427B
skinparam CircleBorderColor<<c4_context>> #08427B
skinparam CircleFontColor<<c4_context>> #fff
skinparam RectangleBackgroundColor<<c4_container>> #438DD5
skinparam RectangleBorderColor<<c4_container>> #073B6F
skinparam RectangleFontColor<<c4_container>> #fff
skinparam QueueBackgroundColor<<c4_container>> #438DD5
skinparam QueueBorderColor<<c4_container>> #073B6F
skinparam QueueFontColor<<c4_container>> #fff
skinparam DatabaseBackgroundColor<<c4_container>> #438DD5
skinparam DatabaseBorderColor<<c4_container>> #073B6F
skinparam DatabaseFontColor<<c4_container>> #fff
skinparam FileBackgroundColor<<c4_container>> #438DD5
skinparam FileBorderColor<<c4_container>> #073B6F
skinparam FileFontColor<<c4_container>> #fff
skinparam HexagonBackgroundColor<<c4_container>> #438DD5
skinparam HexagonBorderColor<<c4_container>> #073B6F
skinparam HexagonFontColor<<c4_container>> #fff
skinparam InterfaceBackgroundColor<<c4_container>> #438DD5
skinparam InterfaceBorderColor<<c4_container>> #073B6F
skinparam InterfaceFontColor<<c4_container>> #fff
skinparam CircleBackgroundColor<<c4_container>> #438DD5
skinparam CircleBorderColor<<c4_container>> #073B6F
skinparam CircleFontColor<<c4_container>> #fff
skinparam RectangleBackgroundColor<<c4_component>> #85BBF0
skinparam RectangleBorderColor<<c4_component>> #78A8D8
skinparam RectangleFontColor<<c4_component>> #000
skinparam QueueBackgroundColor<<c4_component>> #85BBF0
skinparam QueueBorderColor<<c4_component>> #78A8D8
skinparam QueueFontColor<<c4_component>> #000
skinparam DatabaseBackgroundColor<<c4_component>> #85BBF0
skinparam DatabaseBorderColor<<c4_component>> #78A8D8
skinparam DatabaseFontColor<<c4_component>> #000
skinparam FileBackgroundColor<<c4_component>> #85BBF0
skinparam FileBorderColor<<c4_component>> #78A8D8
skinparam FileFontColor<<c4_component>> #000
skinparam HexagonBackgroundColor<<c4_component>> #85BBF0
skinparam HexagonBorderColor<<c4_component>> #78A8D8
skinparam HexagonFontColor<<c4_component>> #000
skinparam InterfaceBackgroundColor<<c4_component>> #85BBF0
skinparam InterfaceBorderColor<<c4_component>> #78A8D8
skinparam InterfaceFontColor<<c4_component>> #000
skinparam CircleBackgroundColor<<c4_component>> #85BBF0
skinparam CircleBorderColor<<c4_component>> #78A8D8
skinparam CircleFontColor<<c4_component>> #000
skinparam RectangleBackgroundColor<<c4_external>> #999999
skinparam RectangleBorderColor<<c4_external>> #8A8A8A
skinparam RectangleFontColor<<c4_external>> #fff
skinparam QueueBackgroundColor<<c4_external>> #999999
skinparam QueueBorderColor<<c4_external>> #8A8A8A
skinparam QueueFontColor<<c4_external>> #fff
skinparam DatabaseBackgroundColor<<c4_external>> #999999
skinparam DatabaseBorderColor<<c4_external>> #8A8A8A
skinparam DatabaseFontColor<<c4_external>> #fff
skinparam FileBackgroundColor<<c4_external>> #999999
skinparam FileBorderColor<<c4_external>> #8A8A8A
skinparam FileFontColor<<c4_external>> #fff
skinparam HexagonBackgroundColor<<c4_external>> #999999
skinparam HexagonBorderColor<<c4_external>> #8A8A8A
skinparam HexagonFontColor<<c4_external>> #fff
skinparam InterfaceBackgroundColor<<c4_external>> #999999
skinparam InterfaceBorderColor<<c4_external>> #8A8A8A
skinparam InterfaceFontColor<<c4_external>> #fff
skinparam CircleBackgroundColor<<c4_external>> #999999
skinparam CircleBorderColor<<c4_external>> #8A8A8A
skinparam CircleFontColor<<c4_external>> #fff

' SYSTEM COLORING
skinparam RectangleBackgroundColor<<system_context>> #08427B
skinparam RectangleBorderColor<<system_context>> #08427B
skinparam RectangleFontColor<<system_context>> #fff
skinparam RectangleBackgroundColor<<system_container>> #438DD5
skinparam RectangleBorderColor<<system_container>> #073B6F
skinparam RectangleFontColor<<system_container>> #fff
skinparam RectangleBackgroundColor<<system_component>> #85BBF0
skinparam RectangleBorderColor<<system_component>> #78A8D8
skinparam RectangleFontColor<<system_component>> #000
skinparam RectangleBackgroundColor<<system_external>> #dddddd
skinparam RectangleBorderColor<<system_external>> #bfbfbf
skinparam RectangleFontColor<<system_external>> #000


' BUSINESS COLORING
skinparam RectangleBackgroundColor<<business_default>> #ede784
skinparam RectangleBorderColor<<business_default>> #ddd202
skinparam RectangleFontColor<<business_default>> #000
skinparam RectangleBackgroundColor<<business_external>> #999999
skinparam RectangleBorderColor<<business_external>> #8A8A8A
skinparam RectangleFontColor<<business_external>> #fff

' ENDPOINT TEXT COLORING
skinparam CircleFontColor #000


skinparam defaultTextAlignment center
skinparam wrapWidth 180
skinparam maxMessageSize 150
skinparam shadowing false

skinparam RectangleWrapWidth 180

' skinparam svgLinkTarget _parent
